### ISSUE TITLE
Can't do repreduction

### ISSUE THREAD

**Issue by CHELSEA234** [chaneyddtt/Convolutional-Sequence-to-Sequence-Model-for-Human-Dynamics#1]
Hi,

I downloaded your code and ran it on my local, and I did averaging over 3 times experiment printing results. I got some numerical values (Fig1), acceptable yet still worse than ones in your paper (Fig2), can you tell me where I made mistakes? BTW, in figure 1, the every row's last value means mean error of all 25 frames.
<img width="510" alt="screen shot 2018-08-10 at 7 23 45 pm" src="https://user-images.githubusercontent.com/24967323/43987266-13c03e52-9cd3-11e8-9b35-950cd21a42fb.png">
![screen shot 2018-07-13 at 3 33 22 pm](https://user-images.githubusercontent.com/24967323/42731058-4274fd92-87ba-11e8-9e57-cbe1fbc536b0.png)

Best,
Xiao Guo

**Comment by CHELSEA234** [comment]
Here is more complete comparison between my questionable reproduction and your published results:
![screen shot 2018-07-15 at 5 06 30 pm](https://user-images.githubusercontent.com/24967323/42739731-701f9aee-8851-11e8-878c-6c687bece2f5.png)

I hope you could give me some hints at this, really appreciate your help!

--------------------------------------------------------------------------------------------
Can you share your save checkpoint file?

**Comment by chaneyddtt** [comment]
Hi Xiao Guo,
Sorry for the late reply. I don't have the original checkpoint file. But I trained my model just now and reached an average error of 1.77 after training for 24000 iterations . I can sent you the checkpoint file if you need. Or you can train more than 20000 iterations(30000 for example) by yourself and choose the best one, which i think can reach a similar average result.

**Comment by zaverichintan** [comment]
Hello @chaneyddtt , 
I will try to follow the steps you mentioned for the number of iterations.
Could you upload the checkpoint file somewhere or send link to the uploaded version?

**Comment by chaneyddtt** [comment]
Hi [@zaverichintan](https://github.com/zaverichintan),
I upload the model [here](https://drive.google.com/file/d/1bHZCH6u7YmloEwzDO--w91qmAmvCcv3A/view?usp=sharing).  Please note that I trained the network again and the result for each action may be slightly different, but the overall average is the same.

**Comment by zaverichintan** [comment]
Hello @chaneyddtt, 
In the zip provided by you, the h5 file is missing. How can I get that? Is it derivable from other files provided?

**Comment by zaverichintan** [comment]
Do I need to run the training once to generate the sample folder?
I have to copy the files you provided and copy them to a folder called Model? 
And then to how to run the AC_main.py with the new model?

**Comment by chaneyddtt** [comment]
Yes, or you can just put the model somewhere you like and specify the path in the AC_main.py. Note that you also have to specify the 'checkpoint' to keep consistent, for example 24000 for the provided model. Then you specify the 'is_sampling' as 'True' before you run the AC_main.py.

**Comment by zaverichintan** [comment]
It throws the error:

`ValueError: Dimensions must be equal, but are 54 and 70 for 'VAESkeleton/add_1' (op: 'Add') with input shapes: [?,1,54,1], [?,1,70,1].
`

**Comment by chaneyddtt** [comment]
Do you set the parameter ''--dataset" to cmu? Because the input dimension is 70 for the cmu dataset, while it is 54 for the human3.6m.

**Comment by zaverichintan** [comment]
Is it possible to get the checkpoint for the Human3.6m dataset, and run the testing on it?

**Comment by chaneyddtt** [comment]
Yes, the checkpoint I provide is for the human3.6m dataset.  Did you set the 'whole_sample_dim' in the Autoenc_gan to [None,50+args.output_length,54,1]. The input dimension should be 54 for the human3.6m dataset.

**Comment by zaverichintan** [comment]
Now it's running without any errors. Thanks
