### ISSUE TITLE
Preprocessing of CMU dataset

### ISSUE THREAD

**Issue by adi-unni** [chaneyddtt/Convolutional-Sequence-to-Sequence-Model-for-Human-Dynamics#16]
Would it be possible to get the matlab file which have the commands for converting the AMC/ASF files from the CMU database into the format given as the instructions given by Graham Taylor are unclear to convert

**Comment by chaneyddtt** [comment]
Hi @Ninjadi12, you can use the ConvertCMU.m file under mhmublv/Motion to convert the data.
