### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by wudonghao** [chaneyddtt/Convolutional-Sequence-to-Sequence-Model-for-Human-Dynamics#2]
Hi, 
Firstly I really appreciated that you shared the code and I am wandering if the datasets format introduction is able to be released. It causes me some trouble to understand data's format when I tried to cite your work.
Looking forward to your reply.

**Comment by CHELSEA234** [comment]
Did you successfully produce all mentioned results in paper?
@wudonghao

**Comment by yanqi1811** [comment]
Hi,
I have the same problem about the data format. How to get this data format from the bvh files? When I want to train it using my bvh files? Looking forward to your reply, thank you very much!

**Comment by chaneyddtt** [comment]
Hi donghao and yanqi,
I am very sorry for the late reply. 
The human3.6m dataset in our experiment is on exponential map format. Actually we directly download the data from [@una-dinosauria](https://github.com/una-dinosauria/human-motion-prediction). You can also refer to file data_utils.py on how to convert this format to other formats such as rotation matrix, quaternion or x,y, z coordinates.
@wudonghao, @yanqi1811

**Comment by sukun1045** [comment]
Hi,
Same question for the CMU mocap dataset, how do you pre-process the C3D/AMC files and convert them into the txt files? Thank you.

**Comment by chaneyddtt** [comment]
Hi,
You can download the bvh file from  [@una-dinosauria](https://github.com/una-dinosauria/cmu-mocap), and then use the tools provided by [@uoguelph-mlrg](https://github.com/uoguelph-mlrg/mhmublv) to process and visualize the data.

**Comment by CraKane** [comment]
Thank you very much for the answer !
